import "./globals.css";

export const metadata = {
  title: "Kiss My Asphalt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="font-roboto">
        {children}
      </body>
    </html>
  );
}
